import { AnimalDef, AnimalType } from './types';

export const ANIMALS: Record<AnimalType, AnimalDef> = {
  [AnimalType.CHICKEN]: {
    id: AnimalType.CHICKEN,
    name: 'Chicken',
    eggColor: 'bg-yellow-200 border-yellow-400',
    eggEmoji: '🥚',
    finalSound: 'Cock-a-doodle-doo! Cluck cluck!',
    stages: [
      { emoji: '🐣', title: 'Hatching', voice: 'Puck' },
      { emoji: '🐣', title: 'Newborn Chick', voice: 'Puck' },
      { emoji: '🐥', title: 'Fluffy Chick', voice: 'Puck' },
      { emoji: '🐥', title: 'Little Bird', voice: 'Puck' },
      { emoji: '🐤', title: 'Growing Bird', voice: 'Kore' },
      { emoji: '🐓', title: 'Young Rooster', voice: 'Fenrir' },
      { emoji: '🐓', title: 'Big Rooster', voice: 'Fenrir' },
      { emoji: '👑🐓', title: 'Royal Rooster', voice: 'Fenrir' },
    ],
  },
  [AnimalType.DINO]: {
    id: AnimalType.DINO,
    name: 'Dino',
    eggColor: 'bg-green-200 border-green-400',
    eggEmoji: '🥚',
    finalSound: 'Rooooaaaar! Grrrrr!',
    stages: [
      { emoji: '🥚', title: 'Cracking Egg', voice: 'Puck' },
      { emoji: '🦖', title: 'Tiny Dino', voice: 'Puck' },
      { emoji: '🦎', title: 'Little Hunter', voice: 'Puck' },
      { emoji: '🦎', title: 'Fast Runner', voice: 'Puck' },
      { emoji: '🐉', title: 'Young Dino', voice: 'Zephyr' },
      { emoji: '🦖', title: 'Big Dino', voice: 'Fenrir' },
      { emoji: '🦖', title: 'T-Rex', voice: 'Fenrir' },
      { emoji: '👑🦖', title: 'King Rex', voice: 'Fenrir' },
    ],
  },
  [AnimalType.DRAGON]: {
    id: AnimalType.DRAGON,
    name: 'Dragon',
    eggColor: 'bg-red-200 border-red-400',
    eggEmoji: '🥚',
    finalSound: 'Whoooosh! Rooooar!',
    stages: [
      { emoji: '🥚', title: 'Hot Egg', voice: 'Puck' },
      { emoji: '🦎', title: 'Baby Dragon', voice: 'Puck' },
      { emoji: '🔥', title: 'Little Spark', voice: 'Puck' },
      { emoji: '🐉', title: 'Smoke Breather', voice: 'Charon' },
      { emoji: '🐉', title: 'Young Drake', voice: 'Charon' },
      { emoji: '🐲', title: 'Flying Dragon', voice: 'Fenrir' },
      { emoji: '🐲', title: 'Fire Dragon', voice: 'Fenrir' },
      { emoji: '👑🐲', title: 'Elder Dragon', voice: 'Fenrir' },
    ],
  },
  [AnimalType.TURTLE]: {
    id: AnimalType.TURTLE,
    name: 'Turtle',
    eggColor: 'bg-emerald-200 border-emerald-400',
    eggEmoji: '🥚',
    finalSound: 'Snap snap! Splash!',
    stages: [
      { emoji: '🐢', title: 'Hatchling', voice: 'Puck' },
      { emoji: '🐢', title: 'Tiny Turtle', voice: 'Puck' },
      { emoji: '💧', title: 'Pond Swimmer', voice: 'Puck' },
      { emoji: '💧', title: 'River Turtle', voice: 'Puck' },
      { emoji: '🐢', title: 'Shell Grower', voice: 'Kore' },
      { emoji: '🌊', title: 'Sea Turtle', voice: 'Fenrir' },
      { emoji: '🌊', title: 'Ocean Traveler', voice: 'Fenrir' },
      { emoji: '👑🐢', title: 'Wise Tortoise', voice: 'Fenrir' },
    ],
  },
  [AnimalType.PENGUIN]: {
    id: AnimalType.PENGUIN,
    name: 'Penguin',
    eggColor: 'bg-blue-200 border-blue-400',
    eggEmoji: '🥚',
    finalSound: 'Honk honk! Squeak!',
    stages: [
      { emoji: '🥚', title: 'Icy Egg', voice: 'Puck' },
      { emoji: '🐧', title: 'Grey Chick', voice: 'Puck' },
      { emoji: '❄️', title: 'Fluffy Ball', voice: 'Puck' },
      { emoji: '🧊', title: 'Ice Slider', voice: 'Puck' },
      { emoji: '🐧', title: 'Young Penguin', voice: 'Kore' },
      { emoji: '🌊', title: 'Fast Swimmer', voice: 'Fenrir' },
      { emoji: '🐧', title: 'Emperor', voice: 'Fenrir' },
      { emoji: '👑🐧', title: 'King Penguin', voice: 'Fenrir' },
    ],
  },
  [AnimalType.OWL]: {
    id: AnimalType.OWL,
    name: 'Owl',
    eggColor: 'bg-amber-200 border-amber-400',
    eggEmoji: '🥚',
    finalSound: 'Hoot hoot! Whoo whoo!',
    stages: [
      { emoji: '🥚', title: 'Nest Egg', voice: 'Puck' },
      { emoji: '🦉', title: 'Baby Owlet', voice: 'Puck' },
      { emoji: '🍂', title: 'Branch Hopper', voice: 'Puck' },
      { emoji: '👀', title: 'Big Eyes', voice: 'Puck' },
      { emoji: '🦉', title: 'Night Flyer', voice: 'Zephyr' },
      { emoji: '🌙', title: 'Moon Watcher', voice: 'Zephyr' },
      { emoji: '🦉', title: 'Wise Owl', voice: 'Fenrir' },
      { emoji: '👑🦉', title: 'Forest Guardian', voice: 'Fenrir' },
    ],
  },
};

export const TOTAL_STAGES = 8;